### ISSUE TITLE
Joining data and types

### ISSUE THREAD

**Issue by EmilAnkerstjerne** [mmvergara/supadart#102]
Is it possible to have typing on joined objects when you introduce joins into your supabase query?

If so, how Can I do that?

If not, is it Planned to be implemented?

**Comment by mmvergara** [comment]
There's no current way but you can do something like this

`final author = Author.fromJson(related_table.author_id as Map<String, dynamic>);`

I don't plan on implementing it, I think that the dart typing system isn't capable doing such thing yet.. and as far as i remember thats why the official supabase flutter sdk is yet to have a typing system just like in javascript (i think).
