### ISSUE TITLE
Request run on local machine

### ISSUE THREAD

**Issue by bookshiyi** [mmvergara/supadart#39]
Thanks for your awesome idea, could we change the project to run on local only by pure dart without `.ts`?

**Comment by mmvergara** [comment]
I'm not entirely clear on the concept. Is the idea to rewrite the generation to work locally without using the API, for offline use? The tool currently relies on `${supabaseUrl}/rest/v1/?apikey=${supabaseAnonKey}` to retrieve schema data, so internet access is required. Could you please provide more details on the goal?

**Comment by bookshiyi** [comment]
According to my understanding,

The current code logic:
`cli(.dart)` --config--> `supadart-server(.ts)` --get--> `supabase-server`
`disk` <--code-- `cli(.dart)` <--json-- `supadart-server(.ts)` <--swagger-- `supabase-server`

Is it possible to reconstruct it into this?
`cli(.dart)` --get--> `supabase-server`
`disk` <--code-- `cli(.dart)` <--swagger-- `supabase-server`

This will facilitate custom generation rules and contribute(debug) code to generators.

**Comment by mmvergara** [comment]
I see, So this will probably remove the generate classes via website right? unless,, maintain dart generators and ts generators

Part of why i made it in nextjs first is:
- Generate via web + can reuse it via serverless api
- Im more comfortable in ts

I can see the clear benefits of what you are proposing, but i'd like to give it some thought

**Comment by bookshiyi** [comment]
> I see, So this will probably remove the generate classes via website right? unless,, maintain dart generators and ts generators
> 
> Part of why i made it in nextjs first is:
> 
> * Generate via web + can reuse it via serverless api
> * Im more comfortable in ts
> 
> I can see the clear benefits of what you are proposing, but i'd like to give it some thought


btw, I also think that the web is very useful for many users, which is convenient for users to get started quickly, and simple tables can easily generate dart code without any installation.

There will indeed be a lot of workload to change to local mode. If you decide to do it, I will be happy to contribute to it.

And, this project is great enough currently, it helped me a lot. I'm glad I didn't meet you later.

**Comment by bookshiyi** [comment]
It may be more difficult to do the type conversion part with pure dart than ts.

Is it possible that use dart to call the local ts code directly, so that the workload will be much less.

**Comment by mmvergara** [comment]
>Is it possible that use dart to call the local ts code directly
done some research, there isn't a way afaik 😔

**Comment by nzlz** [comment]
made a quick PR after reading this issue https://github.com/mmvergara/supadart/pull/41, hopefully i can play a bit with the generation the coming days, not sure if it fully works for me yet.

thanks for the effort btw :) i wish this kind of stuff was suppored directly in supabase ..

**Comment by mmvergara** [comment]
Now i see why is this necessary. the current implementation doesnt work with supabase instances running on local machine? @bookshiyi  @nzlz

**Comment by nzlz** [comment]
the server wont be able to fetch from private local-hosted supa instances
the PR was the smalles change i could think of, but there might be better ways

**Comment by bookshiyi** [comment]
If some one self hosted the supabase server on local network, the supadart vercle server can not  reach it.

**Comment by mmvergara** [comment]
Switched to dart generators.
