### ISSUE TITLE
Generate model class for view

### ISSUE THREAD

**Issue by bookshiyi** [mmvergara/supadart#42]
``` sql
CREATE OR REPLACE VIEW orders_views AS
SELECT 
    o.id AS order_id,
    c.name AS buyer_name,
    o.created_at,
    o.created_by
FROM 
    orders o
JOIN 
    contacts c ON o.buyer_id = c.id;
```

After creating a postgres view, when I tried to use this tool to generate model data, it seemed that the server program crashed and could not return valid data.

**Comment by mmvergara** [comment]
It's fixed for now, it generates models for views, but it also generates, `insert`,`update`, and other methods.
