### ISSUE TITLE
Generate Models with Supabase Local Env (Docker)

### ISSUE THREAD

**Issue by karlreginaldo** [mmvergara/supadart#54]

**Comment by mmvergara** [comment]
@karlreginaldo
make the command line access the `.env` in the project folder to generate the models? Am I understanding this correctly?

**Comment by karlreginaldo** [comment]
ipWhat I mean by local environment is that I want to obtain the generated models while in local development.

Because right now, what’s working is only the Supabase host and the anon key that comes directly from the Supabase.com dashboard

**Comment by mmvergara** [comment]
@karlreginaldo Hmm that's weird... this tool typically works even for local development,

This is an example one for the cli

`dart pub global run supadart -u http://localhost:8000 -k eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJhbm9uIiwKICAgICJpc3MiOiAic3VwYWJhc2UtZGVtbyIsCiAgICAiaWF0IjogMTY0MTc2OTIwMCwKICAgICJleHAiOiAxNzk5NTM1NjAwCn0.dc_X5iR_VP_qT0zsiyj_I_OZ2T9FtRU2BBNWN8Bu4GE`

This one is from the website it also works

![image](https://github.com/user-attachments/assets/c12837dd-9dc4-4d81-bffd-3f5b047ab06c)


could you provide some logs if the cli is giving some?

**Comment by karlreginaldo** [comment]
Using supadart cli with yaml
![image](https://github.com/user-attachments/assets/e54691f8-fbf1-4c91-a50e-73be4d39db5a)
![image](https://github.com/user-attachments/assets/98c13cc0-3665-4e1d-974d-232d3b7eb142)


```
D:\Project\Personal\servebeez-mobile\_packages\servebeez_common> supadart supadart.yaml    
🚀 Supadart v1.4.2                                                                            
==============================
URL:        http://127.0.0.1:54321
ANON KEY:   eyJhbGciOiJIUzI1NiIsInR5c...
Output:     lib/generated/models/
Separated:  true
Dart:       false
Mappings:   null
==============================
Generating...
Error Fetching Supabase Swagger
{"code":"PGRST100","details":"unexpected \"e\" expecting \"not\" or operator (eq, gt, ...)","hint":null,"message":"\"failed to parse filter (eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0)\" (line 1, column 1)"}
Failed to fetch database
```

**Comment by mmvergara** [comment]
Could you try typing this into your browser? `<SUPABASE_URL>/rest/v1/?apikey=<SUPABASE_ANON_KEY>`

this will get the raw swagger json if its correct

ex:
`http://localhost:8000/rest/v1/?apikey=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJhbm9uIiwKICAgICJpc3MiOiAic3VwYWJhc2UtZGVtbyIsCiAgICAiaWF0IjogMTY0MTc2OTIwMCwKICAgICJleHAiOiAxNzk5NTM1NjAwCn0.dc_X5iR_VP_qT0zsiyj_I_OZ2T9FtRU2BBNWN8Bu4GE`


also, make sure that they key ur using is in anon_key.

**Comment by karlreginaldo** [comment]
hmmm this makes sense now.
![image](https://github.com/user-attachments/assets/38649a21-5f28-4f83-847e-470993dd94c5)

**Comment by karlreginaldo** [comment]
btw i tried removing the apikey queryparams and swagger json showed up

`http://127.0.0.1:54321/rest/v1/`
![image](https://github.com/user-attachments/assets/352861e8-e745-47c6-a620-3e751089e875)

**Comment by mmvergara** [comment]
I see the problem now.

You are most likely using the cli for local development (thus the 54321 port)
https://supabase.com/docs/guides/cli/getting-started?queryGroups=platform&platform=npx

and not this self hosting docker part.
https://supabase.com/docs/guides/self-hosting/docker

and based on the query you made it actually behaves different and doesnt need the apikey..

i guess this tool doesn't support (will work on it) this version of local supabase. what i suggest is probably to just recreate the db in an online version of supabase or switch to docker self hosting. will work on solutions for this though.

**Comment by karlreginaldo** [comment]
yeah you're right! I'll switch to self hosting. 

Thanks @mmvergara. you can close this issue

**Comment by mmvergara** [comment]
@karlreginaldo 

should now support cli type of local development

https://github.com/mmvergara/supadart/pull/57
