### ISSUE TITLE
column naming convention

### ISSUE THREAD

**Issue by Achraf-cyber** [mmvergara/supadart#59]
In supabase database. Column are name with lower_snake. I will be great to get the generated classes with all their fields turned to camelCase

**Comment by mmvergara** [comment]
> In supabase database. Column are name with lower_snake. I will be great to get the generated classes with all their fields turned to camelCase

@Achraf-cyber  Thanks for opening an issue! i kinda overlook this. will do it asap.

**Comment by mmvergara** [comment]
@Achraf-cyber  cli now to 1.5.3, please update your cli and try it out. Waiting for your feedback to finalize this issue.
