### ISSUE TITLE
Error when parsing "numeric" in generated code

### ISSUE THREAD

**Issue by Achraf-cyber** [mmvergara/supadart#64]
When I run supadart on a column with type numeric. I get 
```
      col:
          json['col'] != null ? num.tryParse(json['col'].toString()) : 0,
```
The expression evalute to an "num?" rather than a "num" and cause a error when the col is not nullable. This error can be manually solved by replacing the "tryParse" method with a "parse"  method or refactoring to use the null assignment operator

**Comment by mmvergara** [comment]
@Achraf-cyber thanks for opening an issue, will apply the proposed solution in the patch

**Comment by mmvergara** [comment]
@Achraf-cyber, the CLI has been updated. Please check if it's working correctly. I'd appreciate your feedback!

**Comment by Achraf-cyber** [comment]
Yes. It is working correctly thank you
