### ISSUE TITLE
Add Support for dart duration type

### ISSUE THREAD

**Issue by Achraf-cyber** [mmvergara/supadart#75]
When I use this tool to generate dart for supabase, Postgresql `interval` get converted to `String` which makes it difficult to use. But according to `other-types.md` it should be converted to dart `Duration` and it is not runtime tested. May be this tool can be enhanced now to support dart `Duration`

**Comment by mmvergara** [comment]
Bumped cli version to 1.6.1 please update your cli.
Interval type is now supported https://github.com/mmvergara/supadart/pull/76 and also tested
